services:

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
  
  create-topics:
    image: apache/kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Creating topics...'
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic zap-events --bootstrap-server kafka:9092 
      "
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  prisma-studio:
    image: cryptingle/zap-migrations:latest
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/postgres
    ports:
      - "5555:5555"
    command: bun run db:studio
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
  
  db-migrate:
    image: cryptingle/zap-migrations:latest
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

  primary_backend:
    image: cryptingle/zap_primary_backend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    pull_policy: always
    depends_on:
      db-migrate:
        condition: service_completed_successfully

  hooks:
    image: cryptingle/zap-hooks:latest
    ports:
      - "3002:3002"
    restart: unless-stopped
    pull_policy: always
    depends_on:
      db-migrate:
        condition: service_completed_successfully

  processor:
    image: cryptingle/zap-processor:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
  
  worker:
    image: cryptingle/zap-worker:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
  
  web:
    image: cryptingle/zap-web:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3001:3001"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
  

volumes:
  postgres_data: