FROM oven/bun:1-alpine

WORKDIR /app

RUN apk add --no-cache openssl

#Copying workspace files (Good for Docker Layer Caching)
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

# Copying only necessary packages
COPY ./packages/db ./packages/db
COPY ./packages/types ./packages/types

COPY ./apps/hooks ./apps/hooks

RUN bun install --prod

EXPOSE 3002

CMD ["bun", "run", "./apps/hooks/index.ts"]
