FROM oven/bun:1-alpine

WORKDIR /app

RUN apk add --no-cache openssl

#Copying workspace files (Good for Docker Layer Caching)
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

# Copying only necessary packages
COPY ./packages/db ./packages/db
COPY ./packages/types ./packages/types

RUN bun install --prod

RUN bun run db:generate

CMD [ "sh", "-c", "bun run db:migrate" ]