FROM oven/bun:1-alpine

WORKDIR /app

RUN apk add --no-cache openssl

#Copying workspace files (Good for Docker Layer Caching)
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

# Copying only necessary packages
COPY ./packages/db ./packages/db
COPY ./packages/kafka ./packages/kafka

COPY ./apps/processor ./apps/processor

RUN bun install --prod

CMD ["bun", "run", "./apps/hooks/index.ts"]