FROM oven/bun:1-alpine

WORKDIR /app

RUN apk add --no-cache openssl

#Copying workspace files (Good for Docker Layer Caching)
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

#Copying only necessary packages
COPY ./packages/db ./packages/db
COPY ./packages/types ./packages/types
COPY ./packages/ui ./packages/ui
COPY ./packages/eslint-config ./packages/eslint-config
COPY ./packages/typescript-config ./packages/typescript-config

COPY ./apps/web ./apps/web

RUN bun install
RUN bun add -d @types/react @types/node
RUN cd apps/web && bun run build

CMD ["bun", "run", "start:frontend"]